FROM alpine:latest

RUN apk add git curl
COPY download.sh /app/bin/

# Download version {{ VERSION }}
RUN mkdir -p /app/bin && \
    cd /app/bin && \
    ./download.sh "{{ URL }}" github-generate-changelog && \
    chmod +x github-generate-changelog

COPY entrypoint.sh /
ENTRYPOINT ["/entrypoint.sh"]
